### ISSUE TITLE
`tests` as an object as well as an array.

### ISSUE THREAD

**Issue by philcockfield** [practicalmeteor/meteor-munit#4]
I'm thinking it would be really nice to declare tests on the suite declaration from an object, as well as an array (as it is now).  This would make for especially clean declarations in `coffeescript` like this:

```
tests:
  myTest1: (test) -> # Name parsed to "My Test 1"
  myTest2:
    skip: true
    func: (test) -> # Name parsed to "My Test 2"
```

If this sounds interesting, I'll implement that and send you a pull-request.  Does that sound good?
